print("What is your name?")
print("How old are you?")
print("Where are you live?")
Name=input()
Age=input()
City=input()
print("This is", Name)
print("It is",Age)
print("(s)he live in",City)
